version : "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Migrate sqlite3 database"
    cmds:
    - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  migrate_tests:
    aliases:
      - migrate_tests
    desc: "Migrate tests sqlite3 database"
    cmds:
    - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  start:
    desc: "Start SSO server"
    cmds:
    - go run ./cmd/sso/main.go --config="./config/local.yaml"